// ── Tool Definitions ──

export interface ToolParam {
  name: string;
  type: "string" | "number" | "boolean" | "array";
  description: string;
  required?: boolean;
  items?: { type: string };
}

export interface ToolDef {
  name: string;
  description: string;
  parameters: ToolParam[];
  execute: (args: Record<string, unknown>, userId?: string) => Promise<string>;
}

// ── Chat Messages ──

export type Role = "system" | "user" | "assistant" | "tool";

export interface ToolCall {
  id: string;
  name: string;
  arguments: string; // JSON string
}

export interface ChatMessage {
  role: Role;
  content: string;
  reasoning_content?: string;
  tool_calls?: ToolCall[];
  tool_call_id?: string;
}

// ── Stream Events (SSE) ──

export type StreamEvent =
  | { type: "reasoning"; content: string }
  | { type: "text"; content: string }
  | { type: "tool_call_start"; id: string; name: string; arguments: Record<string, unknown> }
  | { type: "tool_call_delta"; id: string; name: string; arguments_delta: string }
  | { type: "tool_call_end"; id: string; arguments: Record<string, unknown> }
  | { type: "tool_result"; id: string; name: string; result: string }
  | { type: "error"; content: string }
  | { type: "done" };

// ── Config ──

export interface McpServerConfig {
  command?: string;
  args?: string[];
  transport: "stdio" | "sse" | "http";
  url?: string; // for SSE / HTTP transport
  headers?: Record<string, string>; // for HTTP transport
}

export interface Config {
  llm: {
    baseUrl: string;
    apiKey: string;
    model: string;
    thinking?: boolean;
    reasoningEffort?: "high" | "max";
  };
  mongodb?: {
    uri: string;
    dbName: string;
  };
  mcpServers?: Record<string, McpServerConfig>;
  server: {
    port: number;
  };
  scheduler?: {
    enabled?: boolean;
    timezone?: string;
    tasks?: {
      nightlyConsolidate?: { enabled?: boolean; cron?: string };
      cleanupOldLogs?: { enabled?: boolean; cron?: string; retentionDays?: number };
      cleanupOldCommitments?: { enabled?: boolean; cron?: string; retentionDays?: number };
    };
  };
  builtinTools?: {
    mode?: "blacklist" | "whitelist"; // default: blacklist
    disabled?: string[]; // for blacklist mode: tool names to disable
    enabled?: string[];  // for whitelist mode: only these tools are available
  };
  cognitive?: {
    autoLevel?: 'manual' | 'semi-auto' | 'full-auto';
    dream?: { threshold?: number; minScore?: number };
    learn?: { minToolCalls?: number };
    retrieval?: { topK?: number };
  };
}

// ── User Memory (OpenClaw-style Markdown) ──

export interface UserMemory {
  userId: string;
  markdown: string;
  updatedAt: number;
}

// ── Skills ──

export interface SkillDoc {
  _id?: string;
  userId?: string; // undefined = builtin/global
  name: string;
  description: string;
  triggers: string[];
  content: string;
  enabled: boolean;
  builtin: boolean;
  createdAt: Date;
}

// ── Session ──

export interface Session {
  id: string;
  messages: ChatMessage[];
  createdAt: number;
}

// ── Cognitive Collections ──

export interface CognitiveCandidateDoc {
  _id?: any;
  userId: string;
  content: string;
  score: number;
  type: 'preference' | 'fact' | 'method' | 'emotion';
  confidence: number;
  source: string;
  stage: 'candidate' | 'rem' | 'promoted' | 'discarded';
  createdAt?: Date;
  expiresAt?: Date;
  decay?: number;
  embedding?: number[];
}

export interface CognitiveSkillDoc {
  _id?: any;
  userId: string;
  name: string;
  description: string;
  content: string;
  version: number;
  confidence: number;
  autoGenerated: boolean;
  sourceConversationIds: string[];
  confirmedAt: Date | null;
  active: boolean;
  createdAt?: Date;
  updatedAt?: Date;
  embedding?: number[];
}
