import type { DbManager } from '../../db.js';
import type { CognitiveConfig } from '../config.js';
import type { CognitiveBus } from '../bus.js';
import type { ExtractedSkill } from './extractor.js';

export class LearnGenerator {
  constructor(
    private bus: CognitiveBus,
    private db: DbManager,
    private config: CognitiveConfig,
  ) {}

  async generate(userId: string, skill: ExtractedSkill, sessionId: string): Promise<boolean> {
    const existingSkills = await this.db.getCognitiveSkills(userId);
    if (existingSkills.some(s => s.name === skill.name && s.active)) {
      console.log(`[LearnGenerator] skill "${skill.name}" already exists, skipping`);
      return false;
    }

    const isFullAuto = this.config.autoLevel === 'full-auto';

    await this.db.addCognitiveSkill({
      userId,
      name: skill.name,
      description: skill.description,
      content: skill.content,
      version: 1,
      confidence: 0.5,
      autoGenerated: true,
      sourceConversationIds: [sessionId],
      confirmedAt: isFullAuto ? new Date() : null,
      active: true,
    });

    await this.bus.emit('learning.skill.generated', {
      userId,
      skill: {
        name: skill.name,
        description: skill.description,
        content: skill.content,
        triggers: skill.triggers,
        autoGenerated: true,
      },
      needsConfirmation: !isFullAuto,
    });

    return true;
  }
}
