import type { ChatMessage } from '../types.js';

export interface ConversationEndPayload {
  userId: string;
  messages: ChatMessage[];
  toolCallCount: number;
}

export interface MemoryCandidateScoredPayload {
  userId: string;
  candidates: Array<{
    content: string;
    score: number;
    type: string;
  }>;
}

export interface DreamPromotePayload {
  userId: string;
  candidates: Array<{
    content: string;
    score: number;
    type: string;
  }>;
}

export interface LearningExtractPayload {
  userId: string;
  messages: ChatMessage[];
  toolCallCount: number;
}

export interface SkillGeneratedPayload {
  userId: string;
  skill: {
    name: string;
    description: string;
    content: string;
    triggers: string[];
    autoGenerated: boolean;
  };
  needsConfirmation: boolean;
}

export interface MemoryQueryPayload {
  userId: string;
  query: string;
}

export interface SkillUsedPayload {
  userId: string;
  skillName: string;
  success: boolean;
}

export type CognitiveEventMap = {
  'conversation.end': ConversationEndPayload;
  'memory.candidate.scored': MemoryCandidateScoredPayload;
  'dream.promote.start': DreamPromotePayload;
  'learning.extract': LearningExtractPayload;
  'learning.skill.generated': SkillGeneratedPayload;
  'memory.query': MemoryQueryPayload;
  'learning.skill.used': SkillUsedPayload;
  'error': Error;
};

type EventName = keyof CognitiveEventMap;
type Handler<E extends EventName> = (payload: CognitiveEventMap[E]) => void | Promise<void>;

export class CognitiveBus {
  private handlers = new Map<EventName, Set<Handler<any>>>();

  on<E extends EventName>(event: E, handler: Handler<E>): void {
    if (!this.handlers.has(event)) {
      this.handlers.set(event, new Set());
    }
    this.handlers.get(event)!.add(handler);
  }

  off<E extends EventName>(event: E, handler: Handler<E>): void {
    this.handlers.get(event)?.delete(handler);
  }

  async emit<E extends EventName>(event: E, payload: CognitiveEventMap[E]): Promise<void> {
    const eventHandlers = this.handlers.get(event);
    if (!eventHandlers) return;
    const promises = [...eventHandlers].map(async (handler) => {
      try {
        await handler(payload);
      } catch (err) {
        this.emit('error', err instanceof Error ? err : new Error(String(err)));
      }
    });
    await Promise.allSettled(promises);
  }
}
