import { describe, it, expect, vi, beforeEach } from 'vitest';
import { LearnGenerator } from '../../../src/cognitive/learn/generator.js';
import { CognitiveBus } from '../../../src/cognitive/bus.js';
import type { DbManager } from '../../../src/db.js';

describe('LearnGenerator', () => {
  let bus: CognitiveBus;
  let mockDb: Partial<DbManager>;

  beforeEach(() => {
    bus = new CognitiveBus();
    mockDb = {
      getCognitiveSkills: vi.fn().mockResolvedValue([]),
      getSkills: vi.fn().mockResolvedValue([]),
      addCognitiveSkill: vi.fn().mockResolvedValue('skill-1'),
    };
  });

  it('should generate a new skill and emit event', async () => {
    const generator = new LearnGenerator(bus, mockDb as any, { autoLevel: 'semi-auto', learn: { skillConfirmRequired: true } } as any);

    const eventSpy = vi.fn();
    bus.on('learning.skill.generated', eventSpy);

    await generator.generate('u1', {
      name: 'test-workflow',
      description: 'A test workflow',
      content: '# Test\n\nSteps here.',
      triggers: ['test', '测试'],
    }, 'session-abc');

    expect(mockDb.addCognitiveSkill).toHaveBeenCalledTimes(1);
    const call = (mockDb.addCognitiveSkill as any).mock.calls[0][0];
    expect(call.confirmedAt).toBeNull();
    expect(call.autoGenerated).toBe(true);
    expect(eventSpy).toHaveBeenCalledTimes(1);
  });

  it('should auto-confirm in full-auto mode', async () => {
    const generator = new LearnGenerator(bus, mockDb as any, { autoLevel: 'full-auto', learn: { skillConfirmRequired: false } } as any);
    await generator.generate('u1', {
      name: 'test-workflow',
      description: 'A test workflow',
      content: '# Test\n\nSteps here.',
      triggers: ['test'],
    }, 'session-abc');

    const call = (mockDb.addCognitiveSkill as any).mock.calls[0][0];
    expect(call.confirmedAt).not.toBeNull();
  });

  it('should skip if skill with same name already exists', async () => {
    mockDb.getCognitiveSkills = vi.fn().mockResolvedValue([
      { name: 'test-workflow', active: true, confirmedAt: new Date() },
    ]);
    const generator = new LearnGenerator(bus, mockDb as any, { autoLevel: 'semi-auto', learn: { skillConfirmRequired: true } } as any);
    await generator.generate('u1', {
      name: 'test-workflow',
      description: 'A test workflow',
      content: '# Test',
      triggers: ['test'],
    }, 'session-abc');

    expect(mockDb.addCognitiveSkill).not.toHaveBeenCalled();
  });
});
