import { describe, it, expect, vi, beforeEach } from 'vitest';
import { LearnIterater } from '../../../src/cognitive/learn/iterater.js';
import { CognitiveBus } from '../../../src/cognitive/bus.js';
import type { DbManager } from '../../../src/db.js';

describe('LearnIterater', () => {
  let bus: CognitiveBus;
  let mockDb: Partial<DbManager>;

  beforeEach(() => {
    bus = new CognitiveBus();
    mockDb = {
      getCognitiveSkills: vi.fn().mockResolvedValue([
        { _id: 's1', name: 'test-skill', content: '# Test\nSteps here.', version: 1, confidence: 0.7, active: true, autoGenerated: true },
      ]),
      updateCognitiveSkillConfidence: vi.fn().mockResolvedValue(undefined),
      updateCognitiveSkillContent: vi.fn().mockResolvedValue(undefined),
      deactivateCognitiveSkill: vi.fn().mockResolvedValue(undefined),
    };
  });

  it('should boost confidence on successful use', async () => {
    const mockOpenai = { chat: { completions: { create: vi.fn() } } };
    const iterater = new LearnIterater(bus, mockDb as any, {
      learn: { confidence: { boost: 0.1, decay: 0.05, minForRevision: 0.3 }, maxSkillVersion: 10 },
    } as any, mockOpenai as any, 'test-model');

    await bus.emit('learning.skill.used', { userId: 'u1', skillName: 'test-skill', success: true });
    expect(mockDb.updateCognitiveSkillConfidence).toHaveBeenCalledWith('s1', expect.closeTo(0.8, 5));
  });

  it('should decrement confidence on failure', async () => {
    const mockOpenai = { chat: { completions: { create: vi.fn() } } };
    const iterater = new LearnIterater(bus, mockDb as any, {
      learn: { confidence: { boost: 0.1, decay: 0.05, minForRevision: 0.3 }, maxSkillVersion: 10 },
    } as any, mockOpenai as any, 'test-model');

    await bus.emit('learning.skill.used', { userId: 'u1', skillName: 'test-skill', success: false });
    expect(mockDb.updateCognitiveSkillConfidence).toHaveBeenCalledWith('s1', expect.closeTo(0.65, 5));
  });

  it('should deactivate skill when confidence drops below threshold', async () => {
    mockDb.getCognitiveSkills = vi.fn().mockResolvedValue([
      { _id: 's1', name: 'test-skill', content: '# Test', version: 1, confidence: 0.32, active: true, autoGenerated: true },
    ]);
    const mockOpenai = { chat: { completions: { create: vi.fn() } } };
    const iterater = new LearnIterater(bus, mockDb as any, {
      learn: { confidence: { boost: 0.1, decay: 0.05, minForRevision: 0.3 }, maxSkillVersion: 10 },
    } as any, mockOpenai as any, 'test-model');

    await bus.emit('learning.skill.used', { userId: 'u1', skillName: 'test-skill', success: false });
    expect(mockDb.deactivateCognitiveSkill).toHaveBeenCalledWith('s1');
  });

  it('should trigger revision after 3 failures', async () => {
    const mockOpenai = {
      chat: { completions: { create: vi.fn().mockResolvedValue({
        choices: [{ message: { content: '# Revised\nBetter steps.' } }],
      }) } },
    };
    const iterater = new LearnIterater(bus, mockDb as any, {
      learn: { confidence: { boost: 0.1, decay: 0.05, minForRevision: 0.3 }, maxSkillVersion: 10 },
    } as any, mockOpenai as any, 'test-model');

    // Emit 3 failures
    for (let i = 0; i < 3; i++) {
      await bus.emit('learning.skill.used', { userId: 'u1', skillName: 'test-skill', success: false });
    }

    expect(mockDb.updateCognitiveSkillContent).toHaveBeenCalledTimes(1);
    expect(mockDb.updateCognitiveSkillContent).toHaveBeenCalledWith('s1', expect.stringContaining('Revised'), 2);
  });

  it('should not act on unknown or inactive skills', async () => {
    mockDb.getCognitiveSkills = vi.fn().mockResolvedValue([
      { _id: 's1', name: 'other-skill', content: '# Other', version: 1, confidence: 0.7, active: false, autoGenerated: true },
    ]);
    const mockOpenai = { chat: { completions: { create: vi.fn() } } };
    const iterater = new LearnIterater(bus, mockDb as any, {
      learn: { confidence: { boost: 0.1, decay: 0.05, minForRevision: 0.3 }, maxSkillVersion: 10 },
    } as any, mockOpenai as any, 'test-model');

    await bus.emit('learning.skill.used', { userId: 'u1', skillName: 'test-skill', success: false });
    expect(mockDb.updateCognitiveSkillConfidence).not.toHaveBeenCalled();
    expect(mockDb.deactivateCognitiveSkill).not.toHaveBeenCalled();
  });

  it('should cap confidence at 1.0', async () => {
    mockDb.getCognitiveSkills = vi.fn().mockResolvedValue([
      { _id: 's1', name: 'test-skill', content: '# Test', version: 1, confidence: 0.95, active: true, autoGenerated: true },
    ]);
    const mockOpenai = { chat: { completions: { create: vi.fn() } } };
    const iterater = new LearnIterater(bus, mockDb as any, {
      learn: { confidence: { boost: 0.1, decay: 0.05, minForRevision: 0.3 }, maxSkillVersion: 10 },
    } as any, mockOpenai as any, 'test-model');

    await bus.emit('learning.skill.used', { userId: 'u1', skillName: 'test-skill', success: true });
    expect(mockDb.updateCognitiveSkillConfidence).toHaveBeenCalledWith('s1', 1.0);
  });
});
