import { describe, it, expect, beforeAll, afterAll } from 'vitest';
import { MongoClient, ObjectId } from 'mongodb';
import { DbManager } from '../../src/db.js';

const TEST_URI = process.env.MONGODB_URI || 'mongodb://localhost:27017/test-cognitive';
const TEST_DB = 'test-cognitive-phase1';
let db: DbManager;
let client: MongoClient;

describe('DbManager cognitive extensions', () => {
  beforeAll(async () => {
    client = new MongoClient(TEST_URI);
    await client.connect();
    db = new DbManager(TEST_URI, TEST_DB);
    await db.connect();
    await client.db(TEST_DB).collection('cognitiveCandidates').deleteMany({});
    await client.db(TEST_DB).collection('cognitiveSkills').deleteMany({});
  });

  afterAll(async () => {
    await client.db(TEST_DB).dropDatabase().catch(() => {});
    await client.close();
  });

  it('should add and get cognitive candidates', async () => {
    await db.addCognitiveCandidate({
      userId: 'u1',
      content: 'User prefers dark mode',
      score: 4,
      type: 'preference',
      confidence: 0.9,
      source: 'session-123',
      stage: 'candidate',
    });
    const candidates = await db.getCognitiveCandidates('u1', 'candidate');
    expect(candidates).toHaveLength(1);
    expect(candidates[0].content).toBe('User prefers dark mode');
    expect(candidates[0].score).toBe(4);
  });

  it('should update candidate stage', async () => {
    const candidates = await db.getCognitiveCandidates('u1', 'candidate');
    const id = candidates[0]._id!.toString();
    await db.updateCandidateStage(id, 'promoted');
    const promoted = await db.getCognitiveCandidates('u1', 'promoted');
    expect(promoted).toHaveLength(1);
  });

  it('should count candidates by stage', async () => {
    const count = await db.countCandidates('u1', 'candidate');
    expect(count).toBe(0);
  });

  it('should add and get cognitive skills', async () => {
    await db.addCognitiveSkill({
      userId: 'u1',
      name: 'test-skill',
      description: 'A test skill',
      content: '# Test Skill\n\nDo something.',
      version: 1,
      confidence: 0.7,
      autoGenerated: true,
      sourceConversationIds: ['s1'],
      confirmedAt: null,
      active: true,
    });
    const skills = await db.getCognitiveSkills('u1');
    expect(skills).toHaveLength(1);
    expect(skills[0].name).toBe('test-skill');
    expect(skills[0].confirmedAt).toBeNull();
  });

  it('should confirm a cognitive skill', async () => {
    const skills = await db.getCognitiveSkills('u1');
    const id = skills[0]._id!.toString();
    await db.confirmCognitiveSkill(id);
    const confirmed = await db.getCognitiveSkills('u1');
    expect(confirmed[0].confirmedAt).not.toBeNull();
  });

  it('should get only active confirmed skills', async () => {
    await db.addCognitiveSkill({
      userId: 'u1',
      name: 'unconfirmed-skill',
      description: 'Not confirmed',
      content: '...',
      version: 1,
      confidence: 0.5,
      autoGenerated: true,
      sourceConversationIds: ['s2'],
      confirmedAt: null,
      active: true,
    });
    const active = await db.getActiveCognitiveSkills('u1');
    expect(active).toHaveLength(1);
    expect(active[0].name).toBe('test-skill');
  });
});
